 @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("check out btn 2")_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Link("SpeakersCategory").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Link("SpeakersCategory")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Image("fetchImage?image_id=4100").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Image("fetchImage?image id4100")_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("quantity").Set "3" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("quantity")_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save_to_cart").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save to cart")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("check_out_btn_3").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("check out btn 3")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("$600.00").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("$1,200.00")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Check CheckPoint("Advantage Shopping") @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Link("ShoppingCart").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Link("ShoppingCart")_;_script infofile_;_ZIP::ssf34.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("REMOVE").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("REMOVE")_;_script infofile_;_ZIP::ssf35.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Your shopping cart is_2").Check CheckPoint("Your shopping cart is empty_2") @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Your shopping cart is 2")_;_script infofile_;_ZIP::ssf36.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Link("Link").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Link("Link")_;_script infofile_;_ZIP::ssf37.xml_;_
